"""Test fixtures for config module tests."""

import os
from pathlib import Path

import pytest


@pytest.fixture
def tmp_project(tmp_path: Path, monkeypatch):
    """
    Create a temporary project directory with kurt.config file.

    This fixture:
    - Creates a temp directory with required subdirectories
    - Creates a basic kurt.config file (legacy format for dot-notation support)
    - Changes cwd to the temp directory
    - Restores original cwd after test

    Yields:
        Path: The temporary project directory

    Note: Tests should use the `config_file` fixture to get the config file path
    instead of calling get_config_file_path() directly.
    """
    # Create required directories
    (tmp_path / ".kurt").mkdir(parents=True, exist_ok=True)
    (tmp_path / "sources").mkdir(parents=True, exist_ok=True)
    (tmp_path / "projects").mkdir(parents=True, exist_ok=True)
    (tmp_path / "rules").mkdir(parents=True, exist_ok=True)

    # Create basic config file using legacy format (kurt.config) to support
    # dot-notation keys like INDEXING.SECTION_EXTRACTIONS.LLM_MODEL in tests.
    # load_config() will fall back to kurt.config if kurt.toml doesn't exist.
    config_file = tmp_path / "kurt.config"
    config_file.write_text(
        """# Kurt Project Configuration
# This file is auto-generated by 'kurt init'

PATH_DB=".kurt/kurt.sqlite"
PATH_SOURCES="sources"
PATH_PROJECTS="projects"
PATH_RULES="rules"
INDEXING_LLM_MODEL="openai/gpt-4o-mini"
ANSWER_LLM_MODEL="openai/gpt-4o"
EMBEDDING_MODEL="openai/text-embedding-3-small"
INGESTION_FETCH_ENGINE="trafilatura"
MAX_CONCURRENT_INDEXING=50

# Telemetry Configuration
TELEMETRY_ENABLED=true
"""
    )

    # Change to temp directory
    original_cwd = os.getcwd()
    os.chdir(tmp_path)

    yield tmp_path

    # Restore original directory
    os.chdir(original_cwd)


@pytest.fixture
def config_file(tmp_project: Path) -> Path:
    """
    Get the path to the test config file.

    This fixture provides the path to the config file created by tmp_project.
    Use this instead of get_config_file_path() in tests that need to read/write
    config values, as it supports dot-notation keys.

    Returns:
        Path: Path to the kurt.config file
    """
    return tmp_project / "kurt.config"
