"""Test fixtures for config module tests."""

import os
from pathlib import Path

import pytest


@pytest.fixture
def tmp_project(tmp_path: Path, monkeypatch):
    """
    Create a temporary project directory with kurt.config file.

    This fixture:
    - Creates a temp directory with required subdirectories
    - Creates a basic kurt.config file
    - Changes cwd to the temp directory
    - Restores original cwd after test

    Yields:
        Path: The temporary project directory
    """
    # Create required directories
    (tmp_path / ".kurt").mkdir(parents=True, exist_ok=True)
    (tmp_path / "sources").mkdir(parents=True, exist_ok=True)
    (tmp_path / "projects").mkdir(parents=True, exist_ok=True)
    (tmp_path / "rules").mkdir(parents=True, exist_ok=True)

    # Create basic config file
    config_file = tmp_path / "kurt.config"
    config_file.write_text(
        """# Kurt Project Configuration
# This file is auto-generated by 'kurt init'

PATH_DB=".kurt/kurt.sqlite"
PATH_SOURCES="sources"
PATH_PROJECTS="projects"
PATH_RULES="rules"
INDEXING_LLM_MODEL="openai/gpt-4o-mini"
ANSWER_LLM_MODEL="openai/gpt-4o"
EMBEDDING_MODEL="openai/text-embedding-3-small"
INGESTION_FETCH_ENGINE="trafilatura"
MAX_CONCURRENT_INDEXING=50

# Telemetry Configuration
TELEMETRY_ENABLED=True
"""
    )

    # Change to temp directory
    original_cwd = os.getcwd()
    os.chdir(tmp_path)

    yield tmp_path

    # Restore original directory
    os.chdir(original_cwd)
